# Build-time environment for the cpal ASIO feature (asio-sys).
# - LIBCLANG_PATH: bindgen loads libclang.dll from here when generating the
#   ASIO bindings. Populated once by copying the libclang.dll from the
#   libclang PyPI wheel (16.0.6) into vendor/libclang/.
# - CPAL_ASIO_DIR: the Steinberg ASIO SDK 2.3.3 sources asio-sys compiles
#   and binds against. Populated once from the asio-sys build-script
#   download into vendor/asio-sdk/.
# Both vendor directories are gitignored (the SDK license does not allow
# redistribution in this repository). Without them the asio feature cannot
# build; plain builds without the feature are unaffected.
[env]
LIBCLANG_PATH = { value = "vendor/libclang", relative = true }
CPAL_ASIO_DIR = { value = "vendor/asio-sdk", relative = true }
