use std::{
    collections::{HashMap, HashSet},
    path::{Path, PathBuf},
    sync::{
        Arc,
        atomic::{AtomicU64, Ordering},
    },
    time::SystemTime,
};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tokio::{
    fs::File,
    io::{AsyncReadExt, AsyncWrite, AsyncWriteExt},
    sync::{Mutex, Semaphore},
};
use tokio_util::sync::CancellationToken;

use super::download_variant::DownloadVariant;
use super::state::{PlaybackProvider, PlaybackTrack};

pub(crate) const LIMITS_MB: [u64; 4] = [256, 512, 1024, 4096];
pub(crate) const BLOCK_SIZE: u64 = 4 * 1024 * 1024;
pub(crate) const CACHE_VERSION: &[u8] = b"ralgrum-audio-cache-v4\0";
pub(crate) const CACHED_DOWNLOAD_INVALID: &str = "The cached audio variant is unavailable";
const MAX_SUPPORTED_TOTAL: u64 = LIMITS_MB[3] * 1024 * 1024;
const DEFAULT_LIMIT_MB: u64 = 512;

fn normalize_limit_mb(limit_mb: u64) -> u64 {
    if LIMITS_MB.contains(&limit_mb) {
        limit_mb
    } else {
        DEFAULT_LIMIT_MB
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub(crate) struct Overview {
    pub(crate) used_bytes: u64,
    pub(crate) max_bytes: u64,
    pub(crate) block_count: u64,
    pub(crate) active_jobs: u64,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum CachedProvider {
    Deezer,
    Soundcloud,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct CachedArtist {
    id: String,
    name: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct CachedTrack {
    provider: CachedProvider,
    id: String,
    title: String,
    artist: String,
    album: String,
    album_id: String,
    release_date: String,
    #[serde(default)]
    artists: Vec<CachedArtist>,
    artwork: String,
    duration: u64,
    #[serde(default)]
    downloadable: bool,
    #[serde(default)]
    progressive: bool,
    explicit: bool,
    service_url: String,
    cache_key: String,
    total: Option<u64>,
}

/// Metadata for one complete cached quality variant. The cache key is the
/// stable local identity generated by the resolver, never a media URL.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct CachedDownload {
    pub(crate) cache_key: String,
    pub(crate) total: u64,
    pub(crate) extension: String,
    pub(crate) format_name: String,
    token: CacheTrackToken,
}

#[derive(Clone, Debug, Eq, Hash, PartialEq)]
struct CacheTarget {
    provider: CachedProvider,
    id: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct CacheTrackToken {
    target: CacheTarget,
    generation: u64,
    global_generation: u64,
}

impl CachedTrack {
    fn from_playback(track: &PlaybackTrack, cache_key: &str, total: Option<u64>) -> Self {
        Self {
            provider: match track.provider {
                PlaybackProvider::Deezer => CachedProvider::Deezer,
                PlaybackProvider::SoundCloud => CachedProvider::Soundcloud,
            },
            id: track.id.clone(),
            title: track.title.clone(),
            artist: track.artist.clone(),
            album: track.album.clone(),
            album_id: track.album_id.clone(),
            release_date: track.release_date.clone(),
            artists: track
                .artists
                .iter()
                .map(|artist| CachedArtist {
                    id: artist.id.clone(),
                    name: artist.name.clone(),
                })
                .collect(),
            artwork: track.artwork.clone(),
            duration: track.duration.as_secs(),
            downloadable: track.downloadable,
            progressive: track.progressive,
            explicit: track.explicit,
            service_url: track.service_url.clone(),
            cache_key: cache_key.to_owned(),
            total,
        }
    }

    fn into_playback(self) -> PlaybackTrack {
        PlaybackTrack {
            provider: match self.provider {
                CachedProvider::Deezer => PlaybackProvider::Deezer,
                CachedProvider::Soundcloud => PlaybackProvider::SoundCloud,
            },
            id: self.id,
            title: self.title,
            artist: self.artist,
            album: self.album,
            album_id: self.album_id,
            release_date: self.release_date,
            artists: self
                .artists
                .into_iter()
                .map(|artist| crate::search::TrackArtistRef {
                    id: artist.id,
                    name: artist.name,
                })
                .collect(),
            artwork: self.artwork,
            duration: std::time::Duration::from_secs(self.duration),
            downloadable: self.downloadable,
            progressive: self.progressive,
            explicit: self.explicit,
            service_url: self.service_url,
        }
    }
}

fn cached_provider(provider: PlaybackProvider) -> CachedProvider {
    match provider {
        PlaybackProvider::Deezer => CachedProvider::Deezer,
        PlaybackProvider::SoundCloud => CachedProvider::Soundcloud,
    }
}

fn parse_cached_key(
    provider: PlaybackProvider,
    track_id: &str,
    cache_key: &str,
) -> Option<(String, String, String)> {
    let provider = match provider {
        PlaybackProvider::Deezer => "deezer",
        PlaybackProvider::SoundCloud => "soundcloud",
    };
    let prefix = format!("{provider}:{track_id}:");
    let remainder = cache_key.strip_prefix(&prefix)?;
    let mut fields = remainder.splitn(3, ':');
    let variant = fields.next()?.trim();
    let extension = fields.next()?.trim().to_ascii_lowercase();
    let format_name = fields.next()?.trim().to_owned();
    if variant.is_empty()
        || format_name.is_empty()
        || !matches!(
            extension.as_str(),
            "flac" | "mp3" | "wav" | "aiff" | "ogg" | "opus" | "aac" | "m4a"
        )
        || format_name.bytes().any(|byte| byte.is_ascii_control())
    {
        return None;
    }
    Some((variant.to_owned(), extension, format_name))
}

fn cached_variant_rank(
    provider: PlaybackProvider,
    requested: DownloadVariant,
    actual_variant: &str,
    extension: &str,
    format_name: &str,
) -> Option<u8> {
    let actual_variant = actual_variant.to_ascii_lowercase();
    let format_name = format_name.to_ascii_lowercase();
    match provider {
        PlaybackProvider::SoundCloud => match requested {
            DownloadVariant::Original if actual_variant == "original" => Some(0),
            DownloadVariant::Murglar if actual_variant == "murglar" => Some(0),
            DownloadVariant::Standard if actual_variant == "standard" => Some(0),
            DownloadVariant::Best => match actual_variant.as_str() {
                "original" => Some(0),
                "murglar" => Some(1),
                "standard" => Some(2),
                _ => None,
            },
            _ => None,
        },
        PlaybackProvider::Deezer => {
            let exact_format = match requested {
                DownloadVariant::DeezerFlac
                | DownloadVariant::Best
                | DownloadVariant::Original
                | DownloadVariant::Murglar
                | DownloadVariant::Standard => extension == "flac" && format_name == "flac",
                DownloadVariant::DeezerMp3_320 => extension == "mp3" && format_name == "mp3_320",
                DownloadVariant::DeezerMp3_128 => extension == "mp3" && format_name == "mp3_128",
            };
            if !exact_format {
                return None;
            }
            match requested {
                DownloadVariant::DeezerFlac
                | DownloadVariant::Best
                | DownloadVariant::Original
                | DownloadVariant::Murglar
                | DownloadVariant::Standard => match actual_variant.as_str() {
                    "murglar" => Some(0),
                    "deezer" => Some(1),
                    _ => None,
                },
                DownloadVariant::DeezerMp3_320 | DownloadVariant::DeezerMp3_128 => {
                    match actual_variant.as_str() {
                        "murglar" => Some(0),
                        "deezer" => Some(1),
                        _ => None,
                    }
                }
            }
        }
    }
}

#[derive(Clone)]
pub(crate) struct AudioCache {
    directory: PathBuf,
    max_bytes: Arc<AtomicU64>,
    generation: Arc<AtomicU64>,
    revision: Arc<AtomicU64>,
    jobs: Arc<Mutex<HashSet<String>>>,
    locks: Arc<Vec<Mutex<()>>>,
    maintenance: Arc<Mutex<()>>,
    track_generations: Arc<Mutex<HashMap<CacheTarget, u64>>>,
    complete_tracks: Arc<std::sync::RwLock<HashSet<CacheTarget>>>,
    prefetch: Arc<Semaphore>,
}

impl AudioCache {
    pub(crate) fn new(directory: PathBuf, limit_mb: u64) -> Self {
        let limit_mb = normalize_limit_mb(limit_mb);
        Self {
            directory,
            max_bytes: Arc::new(AtomicU64::new(limit_mb.saturating_mul(1024 * 1024))),
            generation: Arc::new(AtomicU64::new(0)),
            revision: Arc::new(AtomicU64::new(0)),
            jobs: Arc::new(Mutex::new(HashSet::new())),
            locks: Arc::new((0..32).map(|_| Mutex::new(())).collect()),
            maintenance: Arc::new(Mutex::new(())),
            track_generations: Arc::new(Mutex::new(HashMap::new())),
            complete_tracks: Arc::new(std::sync::RwLock::new(HashSet::new())),
            prefetch: Arc::new(Semaphore::new(1)),
        }
    }

    pub(crate) fn max_bytes(&self) -> u64 {
        self.max_bytes.load(Ordering::Relaxed)
    }

    pub(crate) fn is_known_complete_track(&self, track: &PlaybackTrack) -> bool {
        let target = CacheTarget {
            provider: match track.provider {
                PlaybackProvider::Deezer => CachedProvider::Deezer,
                PlaybackProvider::SoundCloud => CachedProvider::Soundcloud,
            },
            id: track.id.clone(),
        };
        self.complete_tracks
            .read()
            .is_ok_and(|tracks| tracks.contains(&target))
    }
    pub(crate) fn generation(&self) -> u64 {
        self.generation.load(Ordering::SeqCst)
    }
    pub(crate) fn revision(&self) -> u64 {
        self.revision.load(Ordering::Relaxed)
    }
    fn bump_revision(&self) {
        self.revision.fetch_add(1, Ordering::Relaxed);
    }
    pub(crate) fn cancel(&self) {
        self.generation.fetch_add(1, Ordering::SeqCst);
    }

    pub(crate) async fn track_token(
        &self,
        provider: PlaybackProvider,
        track_id: &str,
    ) -> CacheTrackToken {
        let target = CacheTarget {
            provider: match provider {
                PlaybackProvider::Deezer => CachedProvider::Deezer,
                PlaybackProvider::SoundCloud => CachedProvider::Soundcloud,
            },
            id: track_id.to_owned(),
        };
        let generation = self
            .track_generations
            .lock()
            .await
            .get(&target)
            .copied()
            .unwrap_or_default();
        CacheTrackToken {
            target,
            generation,
            global_generation: self.generation(),
        }
    }

    pub(crate) async fn is_track_current(&self, token: Option<&CacheTrackToken>) -> bool {
        let Some(token) = token else {
            return true;
        };
        self.track_generations
            .lock()
            .await
            .get(&token.target)
            .copied()
            .unwrap_or_default()
            == token.generation
            && self.is_current(token.global_generation)
    }

    async fn cancel_track(&self, provider: PlaybackProvider, track_id: &str) {
        let target = CacheTarget {
            provider: match provider {
                PlaybackProvider::Deezer => CachedProvider::Deezer,
                PlaybackProvider::SoundCloud => CachedProvider::Soundcloud,
            },
            id: track_id.to_owned(),
        };
        let mut generations = self.track_generations.lock().await;
        let generation = generations.entry(target).or_default();
        *generation = generation.wrapping_add(1);
    }
    pub(crate) fn job_key(key: &str, total: u64) -> String {
        format!("{key}\0{total}")
    }

    pub(crate) async fn set_limit(&self, limit_mb: u64) -> Result<Overview, String> {
        if !LIMITS_MB.contains(&limit_mb) {
            return Err("Audio cache limit must be 256 MB, 512 MB, 1 GB, or 4 GB".into());
        }
        if self.max_bytes() == limit_mb.saturating_mul(1024 * 1024) {
            return self.overview().await;
        }
        self.cancel();
        self.max_bytes
            .store(limit_mb.saturating_mul(1024 * 1024), Ordering::SeqCst);
        self.bump_revision();
        self.prune().await?;
        self.overview().await
    }

    pub(crate) fn block_path(&self, key: &str, total: u64, start: u64, end: u64) -> PathBuf {
        let mut digest = Sha256::new();
        digest.update(CACHE_VERSION);
        digest.update(key.as_bytes());
        digest.update(b"\0");
        digest.update(total.to_le_bytes());
        digest.update(start.to_le_bytes());
        digest.update(end.to_le_bytes());
        self.directory
            .join(format!("{:x}.block", digest.finalize()))
    }

    fn total_path(&self, key: &str) -> PathBuf {
        let mut digest = Sha256::new();
        digest.update(CACHE_VERSION);
        digest.update(key.as_bytes());
        digest.update(b"\0total");
        self.directory
            .join(format!("{:x}.total", digest.finalize()))
    }

    fn prefetch_marker_path(&self, key: &str, total: u64) -> PathBuf {
        let mut digest = Sha256::new();
        digest.update(CACHE_VERSION);
        digest.update(key.as_bytes());
        digest.update(b"\0prefetch");
        digest.update(total.to_le_bytes());
        self.directory
            .join(format!("{:x}.prefetch", digest.finalize()))
    }

    fn catalog_path(&self) -> PathBuf {
        self.directory.join("tracks-v1.json")
    }

    pub(crate) async fn known_total(&self, key: &str) -> Option<u64> {
        let path = self.total_path(key);
        let value = tokio::fs::read_to_string(path).await.ok()?;
        let total = value.trim().parse::<u64>().ok()?;
        (total > 0 && total <= self.max_bytes()).then_some(total)
    }

    /// Find one complete cache variant for an exact download request. This
    /// scans every catalog record instead of using `cached_tracks`, which
    /// intentionally collapses alternate quality variants into one row.
    pub(crate) async fn complete_download_variant(
        &self,
        track: &PlaybackTrack,
        requested: DownloadVariant,
        cancellation: &CancellationToken,
    ) -> Option<CachedDownload> {
        if track.id.trim().is_empty() || cancellation.is_cancelled() {
            return None;
        }
        let bytes = {
            let _guard = self.maintenance.lock().await;
            tokio::fs::read(self.catalog_path()).await.ok()
        }?;
        let records = serde_json::from_slice::<Vec<CachedTrack>>(&bytes).ok()?;
        let token = self.track_token(track.provider, &track.id).await;
        let provider = cached_provider(track.provider);
        let mut selected: Option<(u8, CachedDownload)> = None;
        for record in records.into_iter().rev() {
            if cancellation.is_cancelled() || !self.is_track_current(Some(&token)).await {
                return None;
            }
            if record.provider != provider || record.id != track.id {
                continue;
            }
            let Some((actual_variant, extension, format_name)) =
                parse_cached_key(track.provider, &track.id, &record.cache_key)
            else {
                continue;
            };
            let Some(rank) = cached_variant_rank(
                track.provider,
                requested,
                &actual_variant,
                &extension,
                &format_name,
            ) else {
                continue;
            };
            let total = match record.total {
                Some(total) if total > 0 && total <= self.max_bytes() => total,
                Some(_) => continue,
                None => match self.known_total(&record.cache_key).await {
                    Some(total) => total,
                    None => continue,
                },
            };
            if tokio::fs::metadata(self.prefetch_marker_path(&record.cache_key, total))
                .await
                .is_ok()
                || !self.is_fully_cached(&record.cache_key, total).await
            {
                continue;
            }
            let cached = CachedDownload {
                cache_key: record.cache_key,
                total,
                extension,
                format_name,
                token: token.clone(),
            };
            if selected
                .as_ref()
                .is_none_or(|(selected_rank, _)| rank < *selected_rank)
            {
                selected = Some((rank, cached));
            }
        }
        selected.map(|(_, cached)| cached)
    }

    /// Copy a complete cached variant to a caller-owned output. Reads are
    /// bounded to one 64 KiB buffer and every block is checked again while
    /// copying, so a stale or corrupt candidate cannot be finalized.
    pub(crate) async fn copy_cached_variant<W>(
        &self,
        cached: &CachedDownload,
        output: &mut W,
        cancellation: &CancellationToken,
        progress: Option<&(dyn Fn(u64, u64) + Send + Sync)>,
    ) -> Result<(), String>
    where
        W: AsyncWrite + Unpin,
    {
        const COPY_BUFFER_SIZE: usize = 64 * 1024;
        if cached.total == 0
            || cached.total > self.max_bytes()
            || cancellation.is_cancelled()
            || !self.is_current(cached.token.global_generation)
            || !self.is_track_current(Some(&cached.token)).await
        {
            return Err("Download request cancelled".into());
        }
        // Keep pruning, cache clearing, and track removal from changing the
        // block set while a cached download is being copied. The checks below
        // still observe cancellation so an invalidated copy exits promptly.
        let _maintenance = self.maintenance.lock().await;
        if cached.total == 0
            || cached.total > self.max_bytes()
            || cancellation.is_cancelled()
            || !self.is_current(cached.token.global_generation)
            || !self.is_track_current(Some(&cached.token)).await
        {
            return Err("Download request cancelled".into());
        }
        let mut buffer = vec![0; COPY_BUFFER_SIZE];
        let mut downloaded = 0_u64;
        let mut start = 0_u64;
        while start < cached.total {
            if cancellation.is_cancelled()
                || !self.is_current(cached.token.global_generation)
                || !self.is_track_current(Some(&cached.token)).await
            {
                return Err("Download request cancelled".into());
            }
            let end = start
                .saturating_add(BLOCK_SIZE.saturating_sub(1))
                .min(cached.total.saturating_sub(1));
            let expected = end.saturating_sub(start).saturating_add(1);
            let path = self.block_path(&cached.cache_key, cached.total, start, end);
            let metadata = tokio::fs::metadata(&path)
                .await
                .map_err(|_| CACHED_DOWNLOAD_INVALID.to_owned())?;
            if !metadata.is_file() || metadata.len() != expected {
                return Err(CACHED_DOWNLOAD_INVALID.into());
            }
            let mut input = File::open(&path)
                .await
                .map_err(|_| CACHED_DOWNLOAD_INVALID.to_owned())?;
            let mut remaining = expected;
            while remaining > 0 {
                let wanted = remaining.min(COPY_BUFFER_SIZE as u64) as usize;
                let count = input
                    .read(&mut buffer[..wanted])
                    .await
                    .map_err(|_| CACHED_DOWNLOAD_INVALID.to_owned())?;
                if count == 0 {
                    return Err(CACHED_DOWNLOAD_INVALID.into());
                }
                if cancellation.is_cancelled()
                    || !self.is_current(cached.token.global_generation)
                    || !self.is_track_current(Some(&cached.token)).await
                {
                    return Err("Download request cancelled".into());
                }
                output
                    .write_all(&buffer[..count])
                    .await
                    .map_err(|_| "The cached audio could not be written".to_owned())?;
                remaining = remaining.saturating_sub(count as u64);
                downloaded = downloaded.saturating_add(count as u64);
                if let Some(progress) = progress {
                    progress(downloaded, cached.total);
                }
            }
            let mut trailing = [0_u8; 1];
            if input
                .read(&mut trailing)
                .await
                .map_err(|_| CACHED_DOWNLOAD_INVALID.to_owned())?
                != 0
            {
                return Err(CACHED_DOWNLOAD_INVALID.into());
            }
            start = end.saturating_add(1);
        }
        output
            .flush()
            .await
            .map_err(|_| "The cached audio could not be flushed".to_owned())?;
        if cancellation.is_cancelled()
            || !self.is_current(cached.token.global_generation)
            || !self.is_track_current(Some(&cached.token)).await
        {
            return Err("Download request cancelled".into());
        }
        Ok(())
    }

    #[cfg(test)]
    pub(crate) async fn remember_total(&self, key: &str, total: u64, generation: u64) {
        self.remember_total_with_token(key, total, generation, None)
            .await;
    }

    pub(crate) async fn remember_total_with_token(
        &self,
        key: &str,
        total: u64,
        generation: u64,
        token: Option<&CacheTrackToken>,
    ) {
        if total == 0
            || total > self.max_bytes()
            || !self.is_current(generation)
            || !self.is_track_current(token).await
        {
            return;
        }
        if tokio::fs::create_dir_all(&self.directory).await.is_err() {
            return;
        }
        let path = self.total_path(key);
        let temporary = path.with_extension(format!("tmp-{}", uuid::Uuid::new_v4().simple()));
        if tokio::fs::write(&temporary, total.to_string())
            .await
            .is_err()
        {
            return;
        }
        let _guard = self.maintenance.lock().await;
        if !self.is_current(generation)
            || !self.is_track_current(token).await
            || tokio::fs::rename(&temporary, &path).await.is_err()
        {
            let _ = tokio::fs::remove_file(&temporary).await;
        } else {
            self.bump_revision();
        }
    }

    /// Persist the reversible metadata needed to enumerate the hashed cache.
    /// The record is only surfaced by `cached_tracks` after every exact block
    /// has been verified, so interrupted playback never appears as playable.
    #[cfg(test)]
    pub(crate) async fn remember_track(
        &self,
        track: &PlaybackTrack,
        cache_key: &str,
        total: Option<u64>,
    ) {
        self.remember_track_with_token(track, cache_key, total, None)
            .await;
    }

    pub(crate) async fn remember_track_with_token(
        &self,
        track: &PlaybackTrack,
        cache_key: &str,
        total: Option<u64>,
        token: Option<&CacheTrackToken>,
    ) {
        if cache_key.is_empty() || track.id.is_empty() {
            return;
        }
        let total = total.filter(|total| *total > 0 && *total <= self.max_bytes());
        if tokio::fs::create_dir_all(&self.directory).await.is_err() {
            return;
        }
        let _guard = self.maintenance.lock().await;
        if !self.is_track_current(token).await {
            return;
        }
        let path = self.catalog_path();
        let mut records = tokio::fs::read(&path)
            .await
            .ok()
            .and_then(|bytes| serde_json::from_slice::<Vec<CachedTrack>>(&bytes).ok())
            .unwrap_or_default();
        let record = CachedTrack::from_playback(track, cache_key, total);
        let mut catalog_changed = true;
        if let Some(existing) = records
            .iter_mut()
            .find(|existing| existing.cache_key == record.cache_key)
        {
            if *existing == record {
                catalog_changed = false;
            } else {
                *existing = record;
            }
        } else {
            records.push(record);
        }
        if catalog_changed {
            let Ok(bytes) = serde_json::to_vec_pretty(&records) else {
                return;
            };
            // The catalog is tiny and the maintenance lock serializes writers.
            // Writing the target directly avoids the non-overwriting rename
            // behavior on Windows when a previous catalog already exists.
            if tokio::fs::write(&path, bytes).await.is_ok() {
                self.bump_revision();
            }
        }
        drop(_guard);
        if let Some(total) = total
            && self.is_fully_cached(cache_key, total).await
            && let Ok(mut complete) = self.complete_tracks.write()
        {
            complete.insert(CacheTarget {
                provider: match track.provider {
                    PlaybackProvider::Deezer => CachedProvider::Deezer,
                    PlaybackProvider::SoundCloud => CachedProvider::Soundcloud,
                },
                id: track.id.clone(),
            });
        }
    }

    /// Return only catalog records whose cache key has a known size and whose
    /// blocks are all present with their exact expected lengths.
    pub(crate) async fn cached_tracks(&self) -> Vec<PlaybackTrack> {
        let path = self.catalog_path();
        let bytes = {
            let _guard = self.maintenance.lock().await;
            tokio::fs::read(path).await.ok()
        };
        let Some(bytes) = bytes else {
            return Vec::new();
        };
        let Some(records) = serde_json::from_slice::<Vec<CachedTrack>>(&bytes).ok() else {
            return Vec::new();
        };
        let mut tracks = Vec::new();
        let mut seen = HashSet::new();
        // Prefer the newest complete quality variant for each logical song,
        // while retaining an older complete variant as a fallback if pruning
        // removed the newer variant's blocks.
        for record in records.into_iter().rev() {
            let total = match record.total {
                Some(total) => Some(total),
                None => self.known_total(&record.cache_key).await,
            };
            let Some(total) = total else {
                continue;
            };
            if tokio::fs::metadata(self.prefetch_marker_path(&record.cache_key, total))
                .await
                .is_ok()
            {
                continue;
            }
            let identity = (record.provider, record.id.clone());
            if !seen.contains(&identity) && self.is_fully_cached(&record.cache_key, total).await {
                seen.insert(identity);
                tracks.push(record.into_playback());
            }
        }
        if let Ok(mut complete) = self.complete_tracks.write() {
            *complete = seen
                .into_iter()
                .map(|(provider, id)| CacheTarget { provider, id })
                .collect();
        }
        tracks
    }

    pub(crate) async fn read(&self, path: &Path, expected: usize) -> Option<Vec<u8>> {
        match tokio::fs::read(path).await {
            Ok(bytes) if bytes.len() == expected => Some(bytes),
            Ok(_) => {
                if tokio::fs::remove_file(path).await.is_ok() {
                    self.bump_revision();
                }
                None
            }
            Err(_) => None,
        }
    }

    #[cfg(test)]
    pub(crate) async fn write(&self, path: &Path, bytes: &[u8], generation: u64) {
        self.write_with_token(path, bytes, generation, None).await;
    }

    pub(crate) async fn write_with_token(
        &self,
        path: &Path,
        bytes: &[u8],
        generation: u64,
        token: Option<&CacheTrackToken>,
    ) {
        if !self.is_current(generation) || !self.is_track_current(token).await {
            return;
        }
        if tokio::fs::create_dir_all(&self.directory).await.is_err() {
            return;
        }
        let temporary = path.with_extension(format!("tmp-{}", uuid::Uuid::new_v4().simple()));
        if tokio::fs::write(&temporary, bytes).await.is_err() {
            return;
        }
        let _guard = self.maintenance.lock().await;
        if !self.is_current(generation)
            || !self.is_track_current(token).await
            || tokio::fs::rename(&temporary, path).await.is_err()
        {
            let _ = tokio::fs::remove_file(&temporary).await;
        } else {
            self.bump_revision();
        }
    }

    /// Mark the first block as speculative prefetch data. The marker contains
    /// only cache-local filenames, never provider URLs or credentials.
    pub(crate) async fn mark_prefetch(
        &self,
        key: &str,
        total: u64,
        generation: u64,
        token: Option<&CacheTrackToken>,
    ) -> bool {
        if key.is_empty()
            || total == 0
            || total > self.max_bytes()
            || !self.is_current(generation)
            || !self.is_track_current(token).await
        {
            return false;
        }
        if tokio::fs::create_dir_all(&self.directory).await.is_err() {
            return false;
        }
        let block_end = total.min(BLOCK_SIZE).saturating_sub(1);
        let block_name = self
            .block_path(key, total, 0, block_end)
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default()
            .to_owned();
        let total_name = self
            .total_path(key)
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default()
            .to_owned();
        let marker_path = self.prefetch_marker_path(key, total);
        let _guard = self.maintenance.lock().await;
        if !self.is_current(generation) || !self.is_track_current(token).await {
            return false;
        }
        if tokio::fs::write(
            marker_path,
            format!("{block_name}\n{total_name}\n{total}\n"),
        )
        .await
        .is_ok()
        {
            self.bump_revision();
            true
        } else {
            false
        }
    }

    /// Promote speculative data to ordinary playback data before a real
    /// playback download starts.
    pub(crate) async fn promote_prefetch(&self, key: &str, total: u64) {
        if key.is_empty() || total == 0 {
            return;
        }
        let _guard = self.maintenance.lock().await;
        if tokio::fs::remove_file(self.prefetch_marker_path(key, total))
            .await
            .is_ok()
        {
            self.bump_revision();
        }
    }

    /// Remove speculative first-block data left by the previous app session.
    /// Normal playback data has no marker and is preserved.
    pub(crate) async fn purge_partial_prefetch(&self) -> Result<u64, String> {
        let _guard = self.maintenance.lock().await;
        let mut entries = match tokio::fs::read_dir(&self.directory).await {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(0),
            Err(error) => return Err(error.to_string()),
        };
        let mut removed = 0;
        while let Some(entry) = entries.next_entry().await.map_err(|e| e.to_string())? {
            let path = entry.path();
            if path.extension().and_then(|value| value.to_str()) != Some("prefetch") {
                continue;
            }
            let marker = tokio::fs::read_to_string(&path).await.unwrap_or_default();
            let mut lines = marker.lines();
            let block_name = lines
                .next()
                .and_then(|value| safe_cache_filename(value, "block"));
            let total_name = lines
                .next()
                .and_then(|value| safe_cache_filename(value, "total"));
            let marker_total = lines
                .next()
                .and_then(|value| value.trim().parse::<u64>().ok());
            let complete_short_prefetch =
                if let (Some(total), Some(filename)) = (marker_total, block_name) {
                    total > 0
                        && total <= BLOCK_SIZE
                        && tokio::fs::metadata(self.directory.join(filename))
                            .await
                            .is_ok_and(|metadata| metadata.is_file() && metadata.len() == total)
                } else {
                    false
                };
            if complete_short_prefetch {
                continue;
            }
            for filename in [block_name, total_name].into_iter().flatten() {
                if tokio::fs::remove_file(self.directory.join(filename))
                    .await
                    .is_ok()
                {
                    removed += 1;
                    self.bump_revision();
                }
            }
            if tokio::fs::remove_file(path).await.is_ok() {
                removed += 1;
                self.bump_revision();
            }
        }
        Ok(removed)
    }

    pub(crate) async fn is_fully_cached(&self, key: &str, total: u64) -> bool {
        if total == 0 || total > self.max_bytes() {
            return false;
        }
        let _guard = self.maintenance.lock().await;
        let mut start = 0;
        while start < total {
            let end = start.saturating_add(BLOCK_SIZE - 1).min(total - 1);
            let expected = end.saturating_sub(start).saturating_add(1);
            let path = self.block_path(key, total, start, end);
            match tokio::fs::metadata(&path).await {
                Ok(metadata) if metadata.is_file() && metadata.len() == expected => {}
                Ok(_) => {
                    if tokio::fs::remove_file(path).await.is_ok() {
                        self.bump_revision();
                    }
                    return false;
                }
                Err(_) => return false,
            }
            start = end.saturating_add(1);
        }
        true
    }

    pub(crate) async fn lock_for(&self, path: &Path) -> tokio::sync::MutexGuard<'_, ()> {
        let index = path
            .file_stem()
            .and_then(|v| v.to_str())
            .and_then(|v| v.get(..8))
            .and_then(|v| u32::from_str_radix(v, 16).ok())
            .unwrap_or_default() as usize
            % self.locks.len();
        self.locks[index].lock().await
    }

    pub(crate) async fn begin_job(&self, key: String) -> bool {
        let inserted = self.jobs.lock().await.insert(key);
        if inserted {
            self.bump_revision();
        }
        inserted
    }
    pub(crate) async fn finish_job(&self, key: &str) {
        if self.jobs.lock().await.remove(key) {
            self.bump_revision();
        }
    }
    pub(crate) async fn permit(&self) -> Option<tokio::sync::OwnedSemaphorePermit> {
        self.prefetch.clone().acquire_owned().await.ok()
    }
    pub(crate) fn is_current(&self, generation: u64) -> bool {
        self.generation.load(Ordering::SeqCst) == generation
    }

    pub(crate) async fn overview(&self) -> Result<Overview, String> {
        tokio::fs::create_dir_all(&self.directory)
            .await
            .map_err(|e| e.to_string())?;
        let mut entries = tokio::fs::read_dir(&self.directory)
            .await
            .map_err(|e| e.to_string())?;
        let mut result = Overview {
            max_bytes: self.max_bytes(),
            active_jobs: self.jobs.lock().await.len() as u64,
            ..Overview::default()
        };
        while let Some(entry) = entries.next_entry().await.map_err(|e| e.to_string())? {
            if entry.path().extension().and_then(|v| v.to_str()) == Some("block")
                && let Ok(metadata) = entry.metadata().await
                && metadata.is_file()
            {
                result.used_bytes = result.used_bytes.saturating_add(metadata.len());
                result.block_count += 1;
            }
        }
        Ok(result)
    }

    pub(crate) async fn prune(&self) -> Result<(), String> {
        let _guard = self.maintenance.lock().await;
        tokio::fs::create_dir_all(&self.directory)
            .await
            .map_err(|e| e.to_string())?;
        let mut entries = tokio::fs::read_dir(&self.directory)
            .await
            .map_err(|e| e.to_string())?;
        let mut blocks = Vec::new();
        let mut used = 0;
        while let Some(entry) = entries.next_entry().await.map_err(|e| e.to_string())? {
            let metadata = match entry.metadata().await {
                Ok(v) => v,
                Err(_) => continue,
            };
            if entry.path().extension().and_then(|v| v.to_str()) == Some("block")
                && metadata.is_file()
            {
                used += metadata.len();
                blocks.push((
                    entry.path(),
                    metadata.len(),
                    metadata.modified().unwrap_or(SystemTime::UNIX_EPOCH),
                ));
            }
        }
        blocks.sort_by_key(|(_, _, modified)| *modified);
        let mut removed_any = false;
        for (path, size, _) in blocks {
            if used <= self.max_bytes() {
                break;
            }
            if tokio::fs::remove_file(path).await.is_ok() {
                used -= size;
                removed_any = true;
                self.bump_revision();
            }
        }
        if removed_any && let Ok(mut complete) = self.complete_tracks.write() {
            complete.clear();
        }
        Ok(())
    }

    pub(crate) async fn clear(&self) -> Result<Overview, String> {
        self.cancel();
        let _guard = self.maintenance.lock().await;
        tokio::fs::create_dir_all(&self.directory)
            .await
            .map_err(|e| e.to_string())?;
        let mut entries = tokio::fs::read_dir(&self.directory)
            .await
            .map_err(|e| e.to_string())?;
        while let Some(entry) = entries.next_entry().await.map_err(|e| e.to_string())? {
            if entry.metadata().await.is_ok_and(|m| m.is_file())
                && tokio::fs::remove_file(entry.path()).await.is_ok()
            {
                self.bump_revision();
            }
        }
        if let Ok(mut complete) = self.complete_tracks.write() {
            complete.clear();
        }
        self.overview().await
    }

    async fn remove_variant_files(
        &self,
        cache_key: &str,
        recorded_total: Option<u64>,
    ) -> Result<(), String> {
        let total = match recorded_total {
            Some(total) => Some(total),
            None => tokio::fs::read_to_string(self.total_path(cache_key))
                .await
                .ok()
                .and_then(|value| value.trim().parse::<u64>().ok()),
        };
        if let Some(total) = total.filter(|total| *total > 0 && *total <= MAX_SUPPORTED_TOTAL) {
            let mut start = 0;
            while start < total {
                let end = start.saturating_add(BLOCK_SIZE - 1).min(total - 1);
                remove_file_if_present(&self.block_path(cache_key, total, start, end)).await?;
                start = end.saturating_add(1);
            }
        }
        remove_file_if_present(&self.total_path(cache_key)).await?;
        Ok(())
    }

    /// Remove every cached quality variant for one provider track.
    ///
    /// Catalog writes, sidecar removal, and block removal all happen under the
    /// maintenance lock so a concurrent catalog read cannot observe a partial
    /// removal. The per-track epoch prevents an in-flight writer from
    /// recreating blocks after this operation completes.
    pub(crate) async fn remove_track(
        &self,
        provider: PlaybackProvider,
        track_id: &str,
    ) -> Result<bool, String> {
        let track_id = track_id.trim();
        if track_id.is_empty() {
            return Ok(false);
        }

        self.cancel_track(provider, track_id).await;
        let _guard = self.maintenance.lock().await;
        let path = self.catalog_path();
        let bytes = match tokio::fs::read(&path).await {
            Ok(bytes) => bytes,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(false),
            Err(error) => return Err(error.to_string()),
        };
        let mut records = serde_json::from_slice::<Vec<CachedTrack>>(&bytes)
            .map_err(|error| format!("could not read cache catalog: {error}"))?;
        let cached_provider = match provider {
            PlaybackProvider::Deezer => CachedProvider::Deezer,
            PlaybackProvider::SoundCloud => CachedProvider::Soundcloud,
        };
        let removed: Vec<CachedTrack> = records
            .iter()
            .filter(|record| record.provider == cached_provider && record.id == track_id)
            .cloned()
            .collect();
        if removed.is_empty() {
            return Ok(false);
        }
        records.retain(|record| record.provider != cached_provider || record.id != track_id);

        let mut variants = HashSet::new();
        for record in removed {
            let total = match record.total {
                Some(total) => Some(total),
                None => tokio::fs::read_to_string(self.total_path(&record.cache_key))
                    .await
                    .ok()
                    .and_then(|value| value.trim().parse::<u64>().ok()),
            };
            if let Some(total) = total.filter(|total| *total > 0 && *total <= MAX_SUPPORTED_TOTAL) {
                variants.insert((record.cache_key, total));
            }
        }

        for (cache_key, total) in variants {
            self.remove_variant_files(&cache_key, Some(total)).await?;
        }

        if records.is_empty() {
            remove_file_if_present(&path).await?;
        } else {
            let bytes = serde_json::to_vec_pretty(&records)
                .map_err(|error| format!("could not write cache catalog: {error}"))?;
            tokio::fs::write(&path, bytes)
                .await
                .map_err(|error| format!("could not write cache catalog: {error}"))?;
        }

        self.bump_revision();
        if let Ok(mut complete) = self.complete_tracks.write() {
            complete.remove(&CacheTarget {
                provider: cached_provider,
                id: track_id.to_owned(),
            });
        }
        Ok(true)
    }
}

async fn remove_file_if_present(path: &Path) -> Result<bool, String> {
    match tokio::fs::remove_file(path).await {
        Ok(()) => Ok(true),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error.to_string()),
    }
}

fn safe_cache_filename<'a>(value: &'a str, extension: &str) -> Option<&'a str> {
    let value = value.trim();
    (!value.is_empty()
        && Path::new(value).file_name().and_then(|name| name.to_str()) == Some(value)
        && Path::new(value).extension().and_then(|name| name.to_str()) == Some(extension))
    .then_some(value)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;
    use tempfile::TempDir;

    fn test_track(id: &str, title: &str) -> PlaybackTrack {
        PlaybackTrack {
            provider: PlaybackProvider::SoundCloud,
            id: id.into(),
            title: title.into(),
            artist: "Artist".into(),
            album: "Album".into(),
            album_id: "album-id".into(),
            release_date: "2026-01-01".into(),
            artists: vec![crate::search::TrackArtistRef {
                id: "artist-id".into(),
                name: "Artist".into(),
            }],
            artwork: "https://example.invalid/art.jpg".into(),
            duration: Duration::from_secs(123),
            downloadable: true,
            progressive: true,
            explicit: true,
            service_url: "https://soundcloud.example/artist/title".into(),
        }
    }

    #[tokio::test]
    async fn limit_block_name_prune_and_cancel_are_deterministic() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let initial_revision = cache.revision();
        assert_eq!(
            AudioCache::new(temp.path().into(), 9999).max_bytes(),
            512 * 1024 * 1024
        );
        assert!(
            AudioCache::new(temp.path().into(), 512)
                .set_limit(513)
                .await
                .is_err()
        );
        let expanded = AudioCache::new(temp.path().into(), 256)
            .set_limit(4096)
            .await
            .unwrap();
        assert_eq!(expanded.max_bytes, 4 * 1024 * 1024 * 1024);
        let path = cache.block_path("track", 10, 0, 9);
        assert_eq!(path.extension().and_then(|v| v.to_str()), Some("block"));
        cache.write(&path, &[1, 2, 3], cache.generation()).await;
        assert!(cache.revision() > initial_revision);
        assert_eq!(cache.overview().await.unwrap().used_bytes, 3);
        cache.set_limit(256).await.unwrap();
        let stale = cache.block_path("stale", 3, 0, 2);
        let generation = cache.generation();
        cache.cancel();
        assert!(!cache.is_current(0));
        cache.write(&stale, &[1, 2, 3], generation).await;
        assert!(!stale.exists());
    }

    #[tokio::test]
    async fn overview_reports_active_cache_jobs() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let initial_revision = cache.revision();
        assert!(cache.begin_job("next-track".into()).await);
        assert_eq!(cache.revision(), initial_revision + 1);
        assert!(!cache.begin_job("next-track".into()).await);
        assert_eq!(cache.revision(), initial_revision + 1);
        assert_eq!(cache.overview().await.unwrap().active_jobs, 1);
        cache.finish_job("next-track").await;
        assert_eq!(cache.revision(), initial_revision + 2);
        cache.finish_job("next-track").await;
        assert_eq!(cache.revision(), initial_revision + 2);
        assert_eq!(cache.overview().await.unwrap().active_jobs, 0);
    }

    #[tokio::test]
    async fn write_creates_a_missing_cache_directory() {
        let temp = TempDir::new().unwrap();
        let directory = temp.path().join("audio-cache");
        let cache = AudioCache::new(directory.clone(), 256);
        let path = cache.block_path("track", 4, 0, 3);

        cache.write(&path, &[1, 2, 3, 4], cache.generation()).await;
        let revision = cache.revision();

        assert_eq!(tokio::fs::read(path).await.unwrap(), vec![1, 2, 3, 4]);
        assert!(directory.is_dir());
        assert_eq!(cache.revision(), revision);
    }

    #[tokio::test]
    async fn total_metadata_is_persistent_and_revisioned() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let generation = cache.generation();
        assert_eq!(cache.known_total("track").await, None);
        cache.remember_total("track", 4, generation).await;
        assert_eq!(cache.known_total("track").await, Some(4));
        assert!(cache.revision() > 0);

        let reopened = AudioCache::new(temp.path().into(), 256);
        assert_eq!(reopened.known_total("track").await, Some(4));
    }

    #[tokio::test]
    async fn v3_blocks_are_not_reused_after_the_cache_key_version_bump() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let key = "deezer:track:deezer:mp3:MP3_320";
        let total: u64 = 4;
        let mut digest = Sha256::new();
        digest.update(b"ralgrum-audio-cache-v3\0");
        digest.update(key.as_bytes());
        digest.update(b"\0");
        digest.update(total.to_le_bytes());
        digest.update(0_u64.to_le_bytes());
        digest.update(3_u64.to_le_bytes());
        let legacy = temp.path().join(format!("{:x}.block", digest.finalize()));
        tokio::fs::create_dir_all(temp.path()).await.unwrap();
        tokio::fs::write(&legacy, b"old!").await.unwrap();

        let current = cache.block_path(key, total, 0, 3);
        assert_ne!(legacy, current);
        assert_eq!(cache.read(&current, 4).await, None);
    }

    #[tokio::test]
    async fn limit_changes_and_clear_advance_revision() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let path = cache.block_path("track", 4, 0, 3);
        cache.write(&path, &[1, 2, 3, 4], cache.generation()).await;

        let before_limit = cache.revision();
        cache.set_limit(512).await.unwrap();
        assert!(cache.revision() > before_limit);

        let before_clear = cache.revision();
        cache.clear().await.unwrap();
        assert!(cache.revision() > before_clear);
    }

    #[tokio::test]
    async fn corrupt_blocks_are_removed_and_revision_is_shared_by_clones() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let clone = cache.clone();
        let path = cache.block_path("track", 4, 0, 3);
        tokio::fs::create_dir_all(temp.path()).await.unwrap();
        tokio::fs::write(&path, [1, 2, 3]).await.unwrap();

        assert!(cache.read(&path, 4).await.is_none());
        assert_eq!(cache.revision(), 1);
        assert_eq!(clone.revision(), 1);
        assert!(!path.exists());
    }

    #[tokio::test]
    async fn catalog_surfaces_only_exactly_complete_blocks() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let track = test_track("track-id", "Before cache");
        let key = "soundcloud:track-id:standard:mp3:MP3_128";
        cache.remember_track(&track, key, Some(4)).await;

        assert!(cache.cached_tracks().await.is_empty());
        let path = cache.block_path(key, 4, 0, 3);
        cache.write(&path, &[1, 2, 3, 4], cache.generation()).await;
        let tracks = cache.cached_tracks().await;
        assert_eq!(tracks.len(), 1);
        assert_eq!(tracks[0], track);

        tokio::fs::write(&path, [1, 2, 3]).await.unwrap();
        assert!(cache.cached_tracks().await.is_empty());
    }

    #[tokio::test]
    async fn exact_download_lookup_preserves_quality_variants() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let track = test_track("track-id", "Quality variants");
        let standard_key = "soundcloud:track-id:standard:mp3:MP3";
        let murglar_key = "soundcloud:track-id:murglar:flac:FLAC";
        let standard_path = cache.block_path(standard_key, 4, 0, 3);
        let murglar_path = cache.block_path(murglar_key, 4, 0, 3);
        cache
            .write(&standard_path, b"std!", cache.generation())
            .await;
        cache.remember_track(&track, standard_key, Some(4)).await;
        cache
            .write(&murglar_path, b"hq!!", cache.generation())
            .await;
        cache.remember_track(&track, murglar_key, Some(4)).await;
        let cancellation = CancellationToken::new();

        let standard = cache
            .complete_download_variant(&track, DownloadVariant::Standard, &cancellation)
            .await
            .expect("standard variant should be discoverable");
        assert_eq!(standard.cache_key, standard_key);
        assert_eq!(standard.extension, "mp3");
        assert_eq!(standard.format_name, "MP3");

        let best = cache
            .complete_download_variant(&track, DownloadVariant::Best, &cancellation)
            .await
            .expect("best variant should prefer the cached high quality");
        assert_eq!(best.cache_key, murglar_key);
        assert_eq!(best.total, 4);
    }

    #[tokio::test]
    async fn exact_download_lookup_skips_incomplete_records_and_separates_deezer_quality() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let mut track = test_track("deezer-id", "Deezer quality variants");
        track.provider = PlaybackProvider::Deezer;
        let stale_key = "deezer:deezer-id:deezer:mp3:MP3_128";
        let flac_key = "deezer:deezer-id:murglar:flac:FLAC";
        cache.remember_track(&track, stale_key, None).await;
        let flac_path = cache.block_path(flac_key, 4, 0, 3);
        cache.write(&flac_path, b"flac", cache.generation()).await;
        cache.remember_track(&track, flac_key, Some(4)).await;
        let cancellation = CancellationToken::new();

        let best = cache
            .complete_download_variant(&track, DownloadVariant::Best, &cancellation)
            .await
            .expect("a complete FLAC variant should survive a stale record");
        assert_eq!(best.cache_key, flac_key);
        assert!(
            cache
                .complete_download_variant(&track, DownloadVariant::DeezerMp3_128, &cancellation)
                .await
                .is_none()
        );

        let mp3_key = "deezer:deezer-id:deezer:mp3:MP3_128";
        let mp3_path = cache.block_path(mp3_key, 4, 0, 3);
        cache.write(&mp3_path, b"mp3!", cache.generation()).await;
        cache.remember_track(&track, mp3_key, Some(4)).await;
        tokio::fs::remove_file(flac_path).await.unwrap();
        assert!(
            cache
                .complete_download_variant(&track, DownloadVariant::Best, &cancellation)
                .await
                .is_none()
        );
        assert!(
            cache
                .complete_download_variant(&track, DownloadVariant::DeezerMp3_128, &cancellation)
                .await
                .is_some()
        );
    }

    #[tokio::test]
    async fn cached_variant_copy_is_cancellation_aware() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let track = test_track("copy-id", "Copy");
        let key = "soundcloud:copy-id:standard:mp3:MP3";
        let total = 128 * 1024 + 17;
        let bytes = (0..total)
            .map(|value| (value % 251) as u8)
            .collect::<Vec<_>>();
        let path = cache.block_path(key, total, 0, total - 1);
        cache.write(&path, &bytes, cache.generation()).await;
        cache.remember_track(&track, key, Some(total)).await;
        let success_cancellation = CancellationToken::new();
        let cached = cache
            .complete_download_variant(&track, DownloadVariant::Standard, &success_cancellation)
            .await
            .expect("complete cache should be copyable");
        let success_path = temp.path().join("copy-success");
        let mut success_output = File::create(&success_path).await.unwrap();
        cache
            .copy_cached_variant(&cached, &mut success_output, &success_cancellation, None)
            .await
            .unwrap();
        drop(success_output);
        assert_eq!(tokio::fs::read(success_path).await.unwrap(), bytes);

        let cancellation = CancellationToken::new();
        let cached = cache
            .complete_download_variant(&track, DownloadVariant::Standard, &cancellation)
            .await
            .expect("complete cache should be copyable");
        let output_path = temp.path().join("copy.part");
        let mut output = File::create(&output_path).await.unwrap();
        let cancel_after_first_chunk = cancellation.clone();
        let progress = move |downloaded: u64, _: u64| {
            if downloaded >= 64 * 1024 {
                cancel_after_first_chunk.cancel();
            }
        };
        let error = cache
            .copy_cached_variant(&cached, &mut output, &cancellation, Some(&progress))
            .await
            .expect_err("cancellation must stop a cache copy");
        drop(output);
        assert_eq!(error, "Download request cancelled");
        let copied = tokio::fs::metadata(output_path).await.unwrap().len();
        assert!(copied >= 64 * 1024 && copied < total);

        tokio::fs::remove_file(&path).await.unwrap();
        let invalid_path = temp.path().join("copy-invalid.part");
        let mut invalid_output = File::create(&invalid_path).await.unwrap();
        let error = cache
            .copy_cached_variant(&cached, &mut invalid_output, &success_cancellation, None)
            .await
            .expect_err("an invalidated candidate must request network fallback");
        assert_eq!(error, CACHED_DOWNLOAD_INVALID);
    }

    #[tokio::test]
    async fn catalog_updates_replace_same_track_and_preserve_metadata() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let first_key = "soundcloud:track-id:standard:mp3:MP3_128";
        let second_key = "soundcloud:track-id:original:mp3:MP3_320";
        let first = test_track("track-id", "First title");
        let second = test_track("track-id", "Updated title");
        let first_path = cache.block_path(first_key, 4, 0, 3);
        let second_path = cache.block_path(second_key, 4, 0, 3);
        cache
            .write(&first_path, &[1, 2, 3, 4], cache.generation())
            .await;
        cache.remember_track(&first, first_key, Some(4)).await;
        cache
            .write(&second_path, &[5, 6, 7, 8], cache.generation())
            .await;
        cache.remember_track(&second, second_key, Some(4)).await;

        let tracks = cache.cached_tracks().await;
        assert_eq!(tracks, vec![second]);
        let records: Vec<CachedTrack> =
            serde_json::from_slice(&tokio::fs::read(cache.catalog_path()).await.unwrap()).unwrap();
        assert_eq!(records.len(), 2);
        assert_eq!(records[0].cache_key, first_key);
        assert_eq!(records[1].cache_key, second_key);

        tokio::fs::remove_file(second_path).await.unwrap();
        assert_eq!(cache.cached_tracks().await, vec![first]);
    }

    #[tokio::test]
    async fn catalog_resolves_size_from_persistent_total_metadata() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let track = test_track("track-id", "Unknown size");
        let key = "soundcloud:track-id:standard:mp3:MP3_128";
        cache.remember_track(&track, key, None).await;
        cache.remember_total(key, 4, cache.generation()).await;
        let path = cache.block_path(key, 4, 0, 3);
        cache.write(&path, &[1, 2, 3, 4], cache.generation()).await;

        assert_eq!(cache.cached_tracks().await, vec![track]);
    }

    #[tokio::test]
    async fn clear_removes_catalog_and_cached_track_listing() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let track = test_track("track-id", "Clear me");
        let key = "soundcloud:track-id:standard:mp3:MP3_128";
        let path = cache.block_path(key, 4, 0, 3);
        cache.write(&path, &[1, 2, 3, 4], cache.generation()).await;
        cache.remember_track(&track, key, Some(4)).await;
        assert!(cache.is_known_complete_track(&track));
        assert_eq!(cache.cached_tracks().await.len(), 1);

        cache.clear().await.unwrap();
        assert!(!cache.is_known_complete_track(&track));
        assert!(cache.cached_tracks().await.is_empty());
        assert!(!cache.catalog_path().exists());
    }

    #[tokio::test]
    async fn startup_prefetch_cleanup_removes_partial_data_but_preserves_complete_tracks() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let complete_key = "complete-track";
        let complete = test_track("complete", "Complete");
        cache
            .remember_total(complete_key, 4, cache.generation())
            .await;
        let complete_path = cache.block_path(complete_key, 4, 0, 3);
        cache
            .write(&complete_path, b"full", cache.generation())
            .await;
        cache.remember_track(&complete, complete_key, Some(4)).await;

        let partial_key = "prefetched-track";
        let partial_total = BLOCK_SIZE + 1;
        assert!(
            cache
                .mark_prefetch(partial_key, partial_total, cache.generation(), None)
                .await
        );
        cache
            .remember_total(partial_key, partial_total, cache.generation())
            .await;
        let partial_path = cache.block_path(partial_key, partial_total, 0, BLOCK_SIZE - 1);
        cache
            .write(
                &partial_path,
                &vec![7; BLOCK_SIZE as usize],
                cache.generation(),
            )
            .await;
        assert!(partial_path.exists());

        let short_key = "short-prefetched-track";
        let short_total = BLOCK_SIZE;
        assert!(
            cache
                .mark_prefetch(short_key, short_total, cache.generation(), None)
                .await
        );
        let short_path = cache.block_path(short_key, short_total, 0, short_total - 1);
        cache
            .write(
                &short_path,
                &vec![8; short_total as usize],
                cache.generation(),
            )
            .await;
        cache
            .remember_track(
                &test_track("short", "Short prefetch"),
                short_key,
                Some(short_total),
            )
            .await;
        assert!(short_path.exists());

        assert!(cache.purge_partial_prefetch().await.unwrap() > 0);
        assert!(!partial_path.exists());
        assert_eq!(cache.known_total(partial_key).await, None);
        assert!(short_path.exists());
        assert!(cache.prefetch_marker_path(short_key, short_total).exists());
        assert_eq!(cache.cached_tracks().await, vec![complete]);
        assert!(cache.is_fully_cached(complete_key, 4).await);
    }

    #[tokio::test]
    async fn promoting_prefetch_keeps_its_block_for_normal_playback() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let key = "promoted-track";
        let total = BLOCK_SIZE + 1;
        assert!(
            cache
                .mark_prefetch(key, total, cache.generation(), None)
                .await
        );
        let path = cache.block_path(key, total, 0, BLOCK_SIZE - 1);
        cache
            .write(&path, &vec![3; BLOCK_SIZE as usize], cache.generation())
            .await;

        cache.promote_prefetch(key, total).await;
        assert!(path.exists());
        assert_eq!(cache.purge_partial_prefetch().await.unwrap(), 0);
        assert!(path.exists());
    }

    #[tokio::test]
    async fn remove_track_removes_all_quality_variants_and_sidecars() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let track = test_track("track-id", "Remove me");
        let first_key = "soundcloud:track-id:standard:mp3:MP3_128";
        let second_key = "soundcloud:track-id:original:mp3:MP3_320";
        let first_path = cache.block_path(first_key, 4, 0, 3);
        let second_path = cache.block_path(second_key, 4, 0, 3);

        cache
            .write(&first_path, &[1, 2, 3, 4], cache.generation())
            .await;
        cache.remember_track(&track, first_key, Some(4)).await;
        cache
            .write(&second_path, &[5, 6, 7, 8], cache.generation())
            .await;
        cache.remember_track(&track, second_key, None).await;
        cache
            .remember_total(second_key, 4, cache.generation())
            .await;
        let before = cache.revision();

        assert!(
            cache
                .remove_track(PlaybackProvider::SoundCloud, "track-id")
                .await
                .unwrap()
        );
        assert!(cache.revision() > before);
        assert!(!first_path.exists());
        assert!(!second_path.exists());
        assert!(!cache.total_path(second_key).exists());
        assert!(cache.cached_tracks().await.is_empty());
        assert!(!cache.catalog_path().exists());
    }

    #[tokio::test]
    async fn remove_track_only_invalidates_selected_track_writes() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let target = test_track("target-id", "Target");
        let other = test_track("other-id", "Other");
        let target_key = "soundcloud:target-id:standard:mp3:MP3_128";
        let other_key = "soundcloud:other-id:standard:mp3:MP3_128";
        let target_path = cache.block_path(target_key, 6, 0, 5);
        let other_path = cache.block_path(other_key, 5, 0, 4);
        let generation = cache.generation();
        let target_token = cache.track_token(target.provider, &target.id).await;
        let other_token = cache.track_token(other.provider, &other.id).await;

        cache
            .write_with_token(&target_path, b"target", generation, Some(&target_token))
            .await;
        cache
            .remember_track_with_token(&target, target_key, Some(6), Some(&target_token))
            .await;
        cache
            .remember_track_with_token(&other, other_key, Some(5), Some(&other_token))
            .await;

        assert!(
            cache
                .remove_track(PlaybackProvider::SoundCloud, &target.id)
                .await
                .unwrap()
        );
        assert!(cache.is_current(generation));
        assert!(!target_path.exists());

        // A stale writer cannot recreate the removed track's block.
        cache
            .write_with_token(&target_path, b"stale!", generation, Some(&target_token))
            .await;
        assert!(!target_path.exists());
        cache
            .remember_total_with_token(target_key, 6, generation, Some(&target_token))
            .await;
        assert!(!cache.total_path(target_key).exists());

        // A new operation for the removed track and an unrelated operation
        // remain valid under the unchanged global generation.
        let fresh_target_token = cache.track_token(target.provider, &target.id).await;
        cache
            .write_with_token(
                &target_path,
                b"fresh!",
                generation,
                Some(&fresh_target_token),
            )
            .await;
        cache
            .remember_track_with_token(&target, target_key, Some(6), Some(&target_token))
            .await;
        assert_eq!(tokio::fs::read(&target_path).await.unwrap(), b"fresh!");

        cache
            .write_with_token(&other_path, b"other", generation, Some(&other_token))
            .await;
        assert_eq!(tokio::fs::read(&other_path).await.unwrap(), b"other");
    }

    #[tokio::test]
    async fn full_cache_detection_requires_every_exact_sized_block() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let key = "track";
        let total = BLOCK_SIZE + 2;
        let first = cache.block_path(key, total, 0, BLOCK_SIZE - 1);
        let last = cache.block_path(key, total, BLOCK_SIZE, total - 1);
        tokio::fs::create_dir_all(temp.path()).await.unwrap();
        tokio::fs::write(&first, vec![1_u8; BLOCK_SIZE as usize])
            .await
            .unwrap();
        assert!(!cache.is_fully_cached(key, total).await);
        tokio::fs::write(&last, [2_u8, 3_u8]).await.unwrap();
        assert!(cache.is_fully_cached(key, total).await);
    }

    #[test]
    fn cache_version_separates_v2_blocks() {
        let temp = TempDir::new().unwrap();
        let cache = AudioCache::new(temp.path().into(), 256);
        let current = cache.block_path("track", 10, 0, 9);
        let old = {
            let mut digest = Sha256::new();
            digest.update(b"ralgrum-audio-cache-v2\0");
            digest.update(b"track");
            digest.update(b"\0");
            digest.update(10_u64.to_le_bytes());
            digest.update(0_u64.to_le_bytes());
            digest.update(9_u64.to_le_bytes());
            temp.path().join(format!("{:x}.block", digest.finalize()))
        };
        assert_ne!(current, old);
    }
}
